/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
int eddiemain(void)
{


	char* str = "this is a test\r\n";


	printfunc(str);

	str = "eva is a stinky butt";
	printfunc(str);
}

printfunc(char*str)
{
	volatile uint32_t * ptr = (volatile uint32_t *)0x40013828;


	for (int i = 0; str[i] != '\0'; i++) {

		volatile uint32_t * isr = (volatile uint32_t *)0x4001381c;
		uint32_t status = *isr;


		while((status & 0x80)!= 0x80){
			isr = (volatile uint32_t *)0x4001381c;
			status = *isr;
		}

		*ptr = (str[i]);

	}

}


//L__usart_isr:
//      .long  0x4001381c

//L__usart_tdr:
//     .long  0x40013828
