/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
int eddiemain(void)
{

/*
	char* str = "10\r\n";
	printfunc(str);

	int num = 12;
	printint(num);
	printfunc("\r\n");


	printint(factorial(num));
	printfunc("\r\n");



	int arr[] = {1, 2, 3};
	int arrlen = sizeof(arr) / sizeof(arr[0]) -1;


	printint(arrlen);
	printfunc("\r\n");
	permute(arr, 0, arrlen);

*/

	printf('hello world');

	/*
	if (num<0){
		printfunc("error");
	}
	else{
		for(int i = 1; i <= num; i++){
			printfunc(fac);
			fac = fac * i;
		}
	}

	printfunc(fac);
	*/

}

printfunc(char* str)
{
	volatile uint32_t * ptr = (volatile uint32_t *)0x40013828;


	for (int i = 0; str[i] != '\0'; i++) {

		volatile uint32_t * isr = (volatile uint32_t *)0x4001381c;
		uint32_t status = *isr;


		while((status & 0x80)!= 0x80){
			isr = (volatile uint32_t *)0x4001381c;
			status = *isr;
		}

		*ptr = (str[i]);

	}

}


void recint(int var, int counter)
{
	volatile uint32_t * ptr = (volatile uint32_t *)0x40013828;

    int r;

    if (counter == 0){
    	return;
    }

    r = var%10;
	volatile uint32_t * isr = (volatile uint32_t *)0x4001381c;
	uint32_t status = *isr;


	while((status & 0x80)!= 0x80){
		isr = (volatile uint32_t *)0x4001381c;
		status = *isr;
	}

    *ptr = r + 0x30;
    counter--;
    recint(var/10, counter);

}

void printint(int var){
	int reverse = 0, remainder, counter =0;

	while( var!= 0){
		remainder = var%10;
		reverse = reverse * 10 + remainder;
		var/=10;
		counter++;
	}

	recint(reverse, counter);
}


int factorial(int num)
{
	if(num>=1)
		return (num * factorial(num-1));
	else{
		return 1;
	}

}

void switchlr(int *l, int *r){

	int temp;
	temp = *l;
	*l = *r;
	*r = temp;
}

//void permutations(string str){

//}

void permute(int *arr, int start, int fin)
{
	if(start == fin){
		int counter = 1;
		for(int i = 0; i < fin+1; i++){
			printint(arr[i]);
			if (counter == 3){
				printfunc("\r\n");
			}
			counter++;
		}
	}

	for(int i = start; i <= fin; i++) // use for loop to point to each position in array
	{
		switchlr((arr+i), (arr+start));
		permute(arr, start+1, fin);
		switchlr((arr+i), (arr+start));
	}

}




//L__usart_isr:
//      .long  0x4001381c
// write a program factorial
// write a program permutations
//L__usart_tdr:
//     .long  0x40013828


